from resin/raspberrypi3-debian:latest

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y

WORKDIR /app
COPY app.py .
COPY requirements.txt .

RUN pip3  install -r requirements.txt
ENTRYPOINT ["python3","app.py"]
