from ubuntu:latest

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y

WORKDIR /app
COPY app.py .
COPY requirements.txt .

RUN pip3 --no-cache-dir install -r requirements.txt
ENTRYPOINT ["python3","app.py"]
